server:
  port: 8989
dubbo:
  application:
    name: service-consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  version: 1.0.0
  scan:
    base-packages: com.example.demo
  consumer:
    timeout: 5000